### ISSUE TITLE
404 when using locale map

### ISSUE THREAD

**Issue by klodeckl** [calien666/persisted-sanitized-routing#2]
I have configured the mapper as in the example described:

        type: PersistedSanitizedPatternMapper
        tableName: tx_extension_domain_model_info
        routeFieldPattern: '^(?P<path_segment>[\w-]+)-(?P<uid>\d+)$'
        routeFieldResult: '{path_segment|sanitized}-{uid}'
        localeMap:
          -
            locale: 'de_DE.*'
            field: path_segment
          -
            locale: 'en_GB.*'
            field: path_segment_en

When I click on the english page the link leads to 404 error. The german version works fine. Do you have a hint what the problem could be?

**Comment by calien666** [comment]
Hey, there's an issue inside the documentation. You should use

`routeFieldPattern: '^(.*)-(?P<uid>\d+)$'`

This should work. I'm working with this config in several projects. Please let me know, if this was helpful.
I will update docs asap.

**Comment by calien666** [comment]
Would be nice to have feedback, if this was helpful for you. Otherwise I'll close this issue within 14 days

**Comment by klodeckl** [comment]
I’ll try again next week.

**Comment by klodeckl** [comment]
It works! Thank you!

**Comment by calien666** [comment]
Thanks for your feedback. I updated the documentation.
