### ISSUE TITLE
Possible without uid in url?

### ISSUE THREAD

**Issue by klodeckl** [calien666/persisted-sanitized-routing#4]
I would like an url without the uid in the url, is that possible? I’m using the mapper just for the localeMap (I have an extension with one record for both languages english and german and an own slug field for each language). So in my case the PersistedAliasMapper would be fine but PersistedAliasMapper does not have the localeMap.

**Comment by klodeckl** [comment]
I solved this now by an own Mapper extending the PersistedAliasMapper and inspiring by your code. Not optimal (in $this->modify(); did not work in function generate so I had to modify findByIdentifier) but works.

**Comment by calien666** [comment]
Hey, as I think, the PersistedAliasMapper should work with the path_segment instead and localized records will have their own path slugs, I don't see any effort.
But I'm working on an extended routing extension with some other features, so if you want to share your code and possibly show the benefit, I#ll try to implement your solution, too.
